version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: 192.168.129.102:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.129.102:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "12301:12301"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.129.102:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=192.168.129.102:2181
      - SERVER_PORT=12301
